// Generated by CoffeeScript 1.8.0
import Ember from 'ember';
var confirmationMixin;

confirmationMixin = Ember.Mixin.create({
  _showConfirmation: function(options) {
    var action;
    if (options == null) {
      options = {};
    }
    action = this.get('action') || this.get('context');
    return this.get('controller').send('openModal', Ember.Object.create({
      actionData: action,
      model: this.get('model'),
      options: options
    }));
  }
});

export default confirmationMixin;
