// Generated by CoffeeScript 1.8.0
var MetaRoute, metaRouteClass;

metaRouteClass = MetaRoute = (function() {
  function MetaRoute() {}

  MetaRoute.map = function(router, callback) {
    this.router = router;
    return callback.call(new metaRouteClass());
  };

  MetaRoute.prototype.resources = function(name) {
    var self;
    self = this;
    return metaRouteClass.router.map(function() {
      this.route(name, {
        path: "/" + name
      });
      this.route("" + name + ".edit", {
        path: self._action_edit_path(name)
      });
      this.route("" + name + ".show", {
        path: self._action_show_path(name)
      });
      return this.route("" + name + ".new", {
        path: self._new_path(name)
      });
    });
  };

  MetaRoute.prototype._action_show_path = function(name) {
    return "/" + name + "/:id/show";
  };

  MetaRoute.prototype._action_edit_path = function(name) {
    return "/" + name + "/:id/edit";
  };

  MetaRoute.prototype._new_path = function(name) {
    return "/" + name + "/new";
  };

  return MetaRoute;

})();

export default metaRouteClass;
