// Generated by CoffeeScript 1.8.0

/*
  This file create navigation menu in top

  @navigate
  @params:
    @title - string
    @options - hash
    @nestedMenu - function

  If you want use another main controller, you must set route param to ""
  for example:
    @navigate "MyDashboard", route: ""

  When you want use Menu group:

    @navigate "Users", ->
      @navigate "Admins"
      @navigate "Managers"

  You can change url for menu when pass url params
      @navigate "Dashboard", url: "/my_dashboard", route: "my_dashboard"

params:
  url
  route
  divider true|false   -> default false
 */

/*
  for testing
    @navigate "System", ->
      @navigate "Users"
      @navigate "Settings", divider: true
 */
import Ember from 'ember';
var navigationClass;

navigationClass  = (function() {
  Navigation.content = [];

  function Navigation(container, parentId) {
    this.parentId = parentId;
    this.container = container || [];
  }

  Navigation.map = function(callback) {
    var navigation;
    navigation = new navigationClass();
    callback.call(navigation);
    return this.content = navigation.container;
  };

  Navigation.prototype.navigate = function(title, options, callback) {
    var emberObject, navigateObject;
    navigateObject = {
      title: title,
      children: [],
      divider: false,
      id: this._uid()
    };
    if (this.parentId) {
      navigateObject.parentId = this.parentId;
    }
    if (options && typeof options !== 'function') {
      navigateObject = Ember.$.extend(navigateObject, options);
    }
    this._makeRoute(navigateObject);
    emberObject = Ember.Object.create(navigateObject);
    this.container.push(emberObject);
    if (typeof options === 'function') {
      callback = options;
    }
    if (callback) {
      emberObject.set('hasChildren', true);
      callback.call(new navigationClass(emberObject.get('children'), emberObject.get('id')));
    }
    return this.container;
  };

  Navigation.prototype._makeRoute = function(options) {
    if (options == null) {
      options = {};
    }
    if (options.route === void 0) {
      return options.route = options.title.dasherize();
    }
  };

  Navigation.prototype._uid = function() {
    return Math.random().toString(36).substr(2, 9);
  };

  Navigation.findParent = function(obj) {
    return this.content.find((function() {
      return function(item) {
        return item.id === obj.parentId;
      };
    })(this));
  };

  return Navigation;

})();

export default navigationClass;
