// Generated by CoffeeScript 1.8.0
import DS from 'ember-data';
var asset;

asset = DS.Model.extend({
  original_filename: DS.attr('string'),
  content_type: DS.attr('string', {
    defaultValue: ""
  }),
  guid: DS.attr('string', {
    defaultValue: ""
  }),
  assetable_id: DS.attr('string'),
  assetable_type: DS.attr('string'),
  thumb_url: DS.attr('string'),
  url: DS.attr('string'),
  type: DS.attr('string', {
    defaultValue: "Asset"
  }),
  is_main: DS.attr('boolean', {
    defaultValue: false
  })
});

export default asset;

// TODO do we need this?
