// Generated by CoffeeScript 1.8.0
import Ember from 'ember';
var siteTitle;

siteTitle = Ember.Object.extend();

siteTitle.reopenClass({
  setup: function(controllerName, model, action) {
    if (action) {
      if (model.get('id')) {
        return document.title = "%@ - %@ - %@".fmt(controllerName, model.get('id'), action);
      } else {
        return document.title = "%@ - %@".fmt(controllerName, action);
      }
    } else {
      return document.title = "%@ - list".fmt(controllerName);
    }
  }
});

export default siteTitle;
