// Generated by CoffeeScript 1.8.0
import Ember from 'ember';
import Attributes from 'ember-cli-admin/dsl/attributes';
var attributesMixin;

attributesMixin = Ember.Mixin.create({
  formAttributes: (function() {
    var attrs;
    attrs = this.get('model.formFields') || Attributes.withoutId(this.get("model").constructor);
    var self = this;
    return attrs.map(function(attr) {
      return {
        name: attr,
        value: self.get('model').get(attr)
      };
    });
  }).property('modelAttributes.@each'),

  tableAttributes: (function() {
    return this.get('modelAttributes');
  }).property('modelAttributes.@each'),

  fileuploads: (function() {
    if (this.get('model.fileuploads')) {
      return this.get('model.fileuploads').map(function(attr) {
        return {
          name: attr
        };
      });
    }
  }).property('model.fileuploads')
});

export default attributesMixin;
