// Generated by CoffeeScript 1.8.0
import Ember from 'ember';
import Attributes from 'ember-cli-admin/dsl/attributes';
var attributesMixin;

attributesMixin = Ember.Mixin.create({
  formAttributes: (function() {
    return Attributes.withoutId(this.get("model").constructor);
  }).property('modelAttributes.@each'),

  tableAttributes: (function() {
    return this.get('modelAttributes');
  }).property('modelAttributes.@each'),

  activeTableAttributes: function(){
    var type = this.toString().match(/:([^:]+)/)[1];
    var hiddenAttributes = this.tableSettingsStore.get(type) || [];
    var attributes = this.get('tableAttributes');
    var returnValue = attributes.filter(function(attr){
      return !hiddenAttributes.some(function(hiddenAttr){
        return hiddenAttr === attr;
      });
    });
    return returnValue;
  }.property(),

  fileuploads: (function() {
    if (this.get('model.fileuploads')) {
      return this.get('model.fileuploads');
    }
  }).property('model.fileuploads')
});

export default attributesMixin;
