// Generated by CoffeeScript 1.8.0
import Ember from 'ember';
var formActionsMixin;

formActionsMixin = Ember.Mixin.create({
    actions: {
        submit: function(redirect) {
            if (redirect == null) {
                redirect = true;
            }
            if (this.get('model.id')) {
                return this._updateModel(redirect);
            } else {
                return this._createModel(redirect);
            }
        },
        cancel: function() {
            if (this.get('model.isDirty')) {
                this.get('model').rollback();
            }
            return this._redirectToTable();
        }
    },
    _redirectToTable: function() {
        return window.history.back();
    },
    _updateModel: function(redirect) {
        var model = this.get('model');
        var self = this;
        return model.save().then(function(){
            if(!Ember.isEmpty(model.get('fileuploads'))){
                model.get('fileuploads').forEach(function(fu){
                    if(!Ember.isEmpty(model.get(fu))){
                        if(model.get(fu).get('length')) {
                           model.get(fu).forEach(function(asset){
                                asset.save();
                            });
                        }
                        else {
                            model.get(fu).save();
                        }
                    }
                });
            }
            if (redirect) {
                return self._redirectToTable();
            }
        });
    },
    _createModel: function(redirect) {
        return this.get('model').save().then((function(_this) {
            return function() {
                if (redirect) {
                    return _this._redirectToTable();
                } else {
                    return _this.send('edit', _this.get('model'));
                }
            };
        })(this));
    }
});

export default formActionsMixin;
