// Generated by CoffeeScript 1.8.0
import Ember from 'ember';
var paginationMixin;

paginationMixin = Ember.Mixin.create({
  queryParams: ['page', 'perPage'],
  page: 1,
  perPage: 25,
  numberOfPages: (function() {
    return Math.ceil(this.get('total') / this.get('perPage'));
  }).property('perPage'),
  onePage: (function() {
    return this.get('numberOfPages') === 1;
  }).property('numberOfPages'),

  actions: {
    changePerPage: function(perPage) {
      return this.set('perPage', perPage);
    }
  }
});

export default paginationMixin;
