// Generated by CoffeeScript 1.8.0
import Ember from 'ember';
import BaseControllerMixin from 'ember-cli-admin/mixins/controllers/base';
var tableViewMixin;

tableViewMixin = Ember.Mixin.create({
  __table: true
});

tableViewMixin.reopen(BaseControllerMixin);

export default tableViewMixin;
