// Generated by CoffeeScript 1.8.0
import Ember from 'ember';
var modelMixin;

modelMixin = Ember.Mixin.create({
  beforeModel: function(transition) {
    this.action = void 0;
    this.page = void 0;
    this.perPage = void 0;
    return this.modelName = this._modelName(transition.targetName);
  },
  model: function(options, transition) {
    this.page = (options != null ? options.page : void 0) || 1;
    this.perPage = (options != null ? options.perPage : void 0) || 25;
    this.q = (options != null ? options.q : void 0);
    this._checkAction(options, transition.targetName);
    if (options.action) {
      this._setAction(options.action);
    }
    if (!this.container.lookupFactory('model:' + this.modelName)) {
      return;
    }
    if (this.store.modelFor(this.modelName)) {
      return this._find_model(this.modelName, options);
    }
  },
  _find_model: function(modelName, options) {
    if (options.action === "new") {
      return this.store.createRecord(modelName, {});
    }
    if (!options.id) {
      var findOptions = {
        page: this.page,
        perPage: this.perPage
      };
      if(!Ember.isEmpty(this.q)){
        findOptions.q = this.q;
      }
      return this.pagination(modelName, findOptions);
    }
    return this.store.find(modelName, options.id);
  },
  _setModel: function(controller, model) {
    if (!model) {
      return;
    }
    if (model.type) {
      return controller.set('model', Ember.Object.create({
        items: model,
        __list: true,
        total: model.meta.total
      }));
    }
    return controller.set('model', model);
  },
  _modelName: function(name) {
    if (/\./.test(name)) {
      name = name.split(".")[0];
    }
    return Ember.String.singularize(name);
  }
});

export default modelMixin;
