// Generated by CoffeeScript 1.8.0
import Ember from 'ember';
var renderMixin;

renderMixin = Ember.Mixin.create({
  renderTemplate: function(controller, model) {
    this._setActiveRoute(controller);
    this._setupBreadscrumbs(controller, model);
    this.render(this._getControllerTemplate(controller), {
      outlet: "main",
      controller: controller
    });
    this._renderNavigation(controller, model);
    this.controllerFor('breadcrumbs').set('resource', model);
    this._renderBreadcrumbs(controller, model);
    this._renderActions(controller, model);
    return this._renderForm(controller, model);
  },
  _renderNavigation: function() {
    return this.render('navigation', {
      outlet: 'navigation',
      controller: 'navigation'
    });
  },
  _renderBreadcrumbs: function() {
    return this.render('breadcrumbs', {
      outlet: 'breadcrumbs',
      controller: 'breadcrumbs'
    });
  },
  _renderActions: function(controller, model) {
    if (model) {
      return this.render('actions', {
        outlet: 'actions',
        controller: controller
      });
    }
  },
  _renderForm: function(controller) {
    if (this.action && (this.action === "edit" || this.action === "new") && this._getControllerTemplate(controller).split('/').length < 2) {
      return this.render(this._getForm(controller), {
        into: this.action,
        outlet: 'form',
        controller: controller
      });
    }
  }
});

export default renderMixin;
